[project]
name = "dspy-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dspy>=3.0.3",
    "python-dotenv>=1.2.1",
]
